// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Z2P-9_MbprDY0KzLbS8iSKGwUP-Ctns',
    appId: '1:289843622791:web:9f9bd0cfe8720aabf95922',
    messagingSenderId: '289843622791',
    projectId: 'whatsapp-clone-a8836',
    authDomain: 'whatsapp-clone-a8836.firebaseapp.com',
    storageBucket: 'whatsapp-clone-a8836.appspot.com',
    measurementId: 'G-DF7PK2LJS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsVuMuPyCFWt-DzbuCY_qRWWzEv3xUfHo',
    appId: '1:289843622791:android:fb4e208da94d1539f95922',
    messagingSenderId: '289843622791',
    projectId: 'whatsapp-clone-a8836',
    storageBucket: 'whatsapp-clone-a8836.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Y2KHQp2be3LbQVL3xNyFCLVAMVd6HG4',
    appId: '1:289843622791:ios:3ac727ef233086d8f95922',
    messagingSenderId: '289843622791',
    projectId: 'whatsapp-clone-a8836',
    storageBucket: 'whatsapp-clone-a8836.appspot.com',
    iosBundleId: 'com.example.whatsappNewUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Y2KHQp2be3LbQVL3xNyFCLVAMVd6HG4',
    appId: '1:289843622791:ios:88bb6e6d39b220c2f95922',
    messagingSenderId: '289843622791',
    projectId: 'whatsapp-clone-a8836',
    storageBucket: 'whatsapp-clone-a8836.appspot.com',
    iosBundleId: 'com.example.whatsappNewUi.RunnerTests',
  );
}
